# This file defines a dictionary of constants that are simply replaced in pnml file (key is replaced by value)
# Used to make the code more readable by avoiding magic numbers
constants = {
    # CARGO IDs 0-14, Base Cargos
    "CARGO_ID_COAL": "1",
    "CARGO_ID_FISH": "10",
    "CARGO_ID_FOOD": "11",
    "CARGO_ID_GOODS": "5",
    "CARGO_ID_GRAIN": "6",
    "CARGO_ID_IRON_ORE": "8",
    "CARGO_ID_LIVESTOCK": "4",
    "CARGO_ID_MAIL":"2",
    "CARGO_ID_OIL": "3",
    "CARGO_ID_PASSENGERS":"0",
    "CARGO_ID_PLASTICS":"12",
    "CARGO_ID_STEEL": "9",
    "CARGO_ID_WOOD": "7",
    "CARGO_ID_TIMBER": "13",
    "CARGO_ID_VEHICLES": "14",
    
    # CARGO IDs BUILDING MATERIAL EXTENSION
    "CARGO_ID_LIMESTONE": "15",
    "CARGO_ID_SAND": "16",
    "CARGO_ID_CEMENT": "17",
    "CARGO_ID_BUILDING_MATERIALS": "18",
    
    # CARGO IDs TEXTILE INDUSTRIES EXTENSION
    "CARGO_ID_TEXTILES": "20",
    "CARGO_ID_WOOL": "19",
    
    # CARGO IDs ALUMINIUM EXTENSION
    "CARGO_ID_ALUMINIUM": "21",
    "CARGO_ID_BAUXITE": "22",
    
    # CARGO IDs BASIC INORGANIC CHEMISTRY EXTENSION
    "CARGO_ID_CHLORINE": "24",
    "CARGO_ID_HYDROGEN": "26",
    "CARGO_ID_LYE": "25",
    "CARGO_ID_SALT": "23",
    
    # CARGO IDs PAINTINGS INDUSTRIES
    "CARGO_ID_CARBON_BLACK": "29",
    "CARGO_ID_COPPER_ORE": "27",
    "CARGO_ID_COPPER": "28",
    "CARGO_ID_PAINT": "30",
    
    # CARGO IDs FOOD INDUSTRY
    "CARGO_ID_MILK": "31",
    
    # CARGO IDs PACKAGING INDUSTRY
    "CARGO_ID_PACKAGING" : "32",
    
    # CARGO IDs GLASS
    "CARGO_ID_GLASS": "34",
    "CARGO_ID_QUICKLIME": "33",
    
    # CARGO IDs PAPER
    "CARGO_ID_PAPER": "35",
    
    # CARGO IDs ORGANIC CHEMISTRY
    "CARGO_ID_ETHYLENE": "37",
    "CARGO_ID_NAPHTHA" : "36",    
    "CARGO_ID_PETROL" : "38",
    
    # CARGO IDs COKE SULPHUR
    "CARGO_ID_ACID" : "42",
    "CARGO_ID_COKE" : "39",
    "CARGO_ID_PYRITE_ORE" : "40",
    "CARGO_ID_SULPHUR" : "41",
    
    # CARGO IDs AMMONIA
    "CARGO_ID_AMMONIA" : "45",
    "CARGO_ID_N2" : "44",
    "CARGO_ID_O2" : "43",
    "CARGO_ID_SODA" : "46",
    
    # CARGO IDs FRUITS
    "CARGO_ID_BIOMASS" : "48",
    "CARGO_ID_FRUITS" : "47",
        
    # INDUSTRY IDS 0-20 (with gaps): Base Industries
    "INDUSTRY_ID_BUILDERS_YARD":"17",
    "INDUSTRY_ID_COAL_MINE": "0",
    "INDUSTRY_ID_DEPARTMENT_STORE": "15",
    "INDUSTRY_ID_FURNITURE_FACTORY":"6",
    "INDUSTRY_ID_FARM":"9",
    "INDUSTRY_ID_FISHING_GROUNDS":"10",
    "INDUSTRY_ID_FOOD_PROCESSOR": "12",
    "INDUSTRY_ID_FOREST":"3",
    "INDUSTRY_ID_GENERAL_STORE":"14",
    "INDUSTRY_ID_HOTEL":"19",
    "INDUSTRY_ID_INTEGRATED_STEEL_MILL":"8",
    "INDUSTRY_ID_IRON_ORE_MINE":"18",
    "INDUSTRY_ID_OIL_RIG":"5",
    "INDUSTRY_ID_OIL_WELL":"11",
    "INDUSTRY_ID_PLASTICS_PLANT":"4",
    "INDUSTRY_ID_PORT":"20",
    "INDUSTRY_ID_POWER_PLANT": "1",
    "INDUSTRY_ID_SAWMILL":"2",
    "INDUSTRY_ID_VEHICLE_DISTRIBUTOR":"16",
    "INDUSTRY_ID_VEHICLE_FACTORY":"13",
    
    # Building Material Extension
    "INDUSTRY_ID_BRICK_WORKS": "24",
    "INDUSTRY_ID_LIMESTONE_MINE": "21",
    "INDUSTRY_ID_SANDPIT": "22",
    "INDUSTRY_ID_CEMENT_PLANT": "23",
    
    # Textile Industries Extension
    "INDUSTRY_ID_CLOTHING_PLANT": "26",
    "INDUSTRY_ID_TEXTILE_MILL": "25",
    
    # Aluminium Extension
    "INDUSTRY_ID_ALUMINIUM_PLANT": "27",
    
    # Basic Inorganic Chemistry Extension
    "INDUSTRY_ID_CHLOR_ALKALI_PLANT": "29",
    "INDUSTRY_ID_PHARMACEUTICAL_PLANT": "30",
    "INDUSTRY_ID_SALT_MINE": "28",
    
    # Paint Industries Extension
    "INDUSTRY_ID_CARBON_BLACK_PLANT": "33",
    "INDUSTRY_ID_COPPER_ORE_MINE": "31",
    "INDUSTRY_ID_COPPER_SMELTER": "32",
    "INDUSTRY_ID_PAINT_FACTORY": "34",
    
    # Food Industries Extension
    "INDUSTRY_ID_ANIMAL_FARM" : "39",
    "INDUSTRY_ID_BREWERY" : "35",
    "INDUSTRY_ID_DAIRY" : "38",
    "INDUSTRY_ID_FLOUR_MILL" : "36",
    "INDUSTRY_ID_STOCKYARD" : "37",
    
    # Packaging Industries Extension
    "INDUSTRY_ID_PACKAGING_PLANT" : "40",
    
    # Glass Extension
    "INDUSTRY_ID_GLASS_WORKS" : "42",
    "INDUSTRY_ID_LIME_KILN" : "41",
    
    # Paper Extension
    "INDUSTRY_ID_PAPER_MILL" : "43",
    "INDUSTRY_ID_PRINTING_WORKS" : "7", # original ID of the builtin printing works
    
    # Organic Chemistry Extension
    "INDUSTRY_ID_COAL_LIQUEFACTION_PLANT" : "47",
    "INDUSTRY_ID_OIL_REFINERY" : "44",
    "INDUSTRY_ID_PETROL_STATION" : "48",
    "INDUSTRY_ID_STEAMCRACKER" : "46",
    "INDUSTRY_ID_STEAMREFORMER" : "45",  

    # Coke Sulphur Extension
    "INDUSTRY_ID_ACID_PLANT": "50",
    "INDUSTRY_ID_COKE_OVEN": "49",
    "INDUSTRY_ID_ORE_SMELTER": "51",
    
    # Ammonia Extension
    "INDUSTRY_ID_AMMONIA_PLANT": "53",
    "INDUSTRY_ID_CLEANING_PRODUCTS_FACTORY": "55",
    "INDUSTRY_ID_CRYO_PLANT": "52",    
    "INDUSTRY_ID_SODA_PLANT": "54",
    
    # Fruits Extension
    "INDUSTRY_ID_FRUIT_PLANTATION":"56",
    "INDUSTRY_ID_BIOREFINERY":"57",
    
    # INDUSTRY TILE IDs for Base Industries
    "INDUSTRY_TILE_ID_BUILDERS_YARD":"22",
    "INDUSTRY_TILE_ID_COAL_MINE_1": "0",
    "INDUSTRY_TILE_ID_COAL_MINE_2": "1",
    "INDUSTRY_TILE_ID_DEPARTMENT_STORE":"20",
    "INDUSTRY_TILE_ID_FURNITURE_FACTORY":"15",
    "INDUSTRY_TILE_ID_FARM":"14",
    "INDUSTRY_TILE_ID_FISHING_GROUNDS":"16",
    "INDUSTRY_TILE_ID_FOOD_PROCESSOR": "17",
    "INDUSTRY_TILE_ID_FOREST_1":"11",
    "INDUSTRY_TILE_ID_FOREST_2":"12",
    "INDUSTRY_TILE_ID_GENERAL_STORE":"19",
    "INDUSTRY_TILE_ID_HOTEL":"23",
    "INDUSTRY_TILE_ID_INTEGRATED_STEEL_MILL_1":"8",
    "INDUSTRY_TILE_ID_INTEGRATED_STEEL_MILL_2":"9",
    "INDUSTRY_TILE_ID_IRON_ORE_MINE_1": "5",
    "INDUSTRY_TILE_ID_IRON_ORE_MINE_2": "6",
    "INDUSTRY_TILE_ID_IRON_ORE_MINE_3": "7",
    "INDUSTRY_TILE_ID_PLASTICS_PLANT":"10",
    "INDUSTRY_TILE_ID_OIL_RIG":"24",
    "INDUSTRY_TILE_ID_OIL_WELL_ANIM": "4",
    "INDUSTRY_TILE_ID_OIL_WELL":"3",
    "INDUSTRY_TILE_ID_PORT_1":"25",
    "INDUSTRY_TILE_ID_PORT_2":"26",
    "INDUSTRY_TILE_ID_POWER_PLANT_ANIM":"2",
    "INDUSTRY_TILE_ID_SAWMILL_1":"13",
    "INDUSTRY_TILE_ID_VEHICLE_DISTRIBUTOR":"21",
    "INDUSTRY_TILE_ID_VEHICLE_FACTORY":"18",

    # TILE IDs for BUILDING MATERIAL EXTENSION
    "INDUSTRY_TILE_ID_BRICK_WORKS":"33",
    "INDUSTRY_TILE_ID_CEMENT_PLANT":"32",
    "INDUSTRY_TILE_ID_LIMESTONE_MINE_1": "27",
    "INDUSTRY_TILE_ID_LIMESTONE_MINE_2": "28",
    "INDUSTRY_TILE_ID_LIMESTONE_MINE_3": "29",
    "INDUSTRY_TILE_ID_SANDPIT_1":"30",
    "INDUSTRY_TILE_ID_SANDPIT_2":"31",
    
    # TILE IDs for TEXTILE INDUSTRIES EXTENSION
    "INDUSTRY_TILE_ID_TEXTILE_MILL": "34",
    "INDUSTRY_TILE_ID_CLOTHING_PLANT": "35",
    
    # TILE IDs for ALUMINIUM EXTENSION
    "INDUSTRY_TILE_ID_ALUMINIUM_PLANT": "36",
    
    # TILE IDs for BASIC_INORGANIC_CHEMISTRY_EXTENSION
    "INDUSTRY_TILE_ID_CHLOR_ALKALI_PLANT_1": "40",
    "INDUSTRY_TILE_ID_CHLOR_ALKALI_PLANT_2": "41",
    "INDUSTRY_TILE_ID_PHARMACEUTICAL_PLANT_1": "42",
    "INDUSTRY_TILE_ID_PHARMACEUTICAL_PLANT_2": "43",
    "INDUSTRY_TILE_ID_SALT_MINE_1": "37",
    "INDUSTRY_TILE_ID_SALT_MINE_2": "38",
    "INDUSTRY_TILE_ID_SALT_MINE_3": "39",
    
    # TILE IDs for PAINT_INDUSTRIES EXTENSION
    "INDUSTRY_TILE_ID_CARBON_BLACK_PLANT": "46",
    "INDUSTRY_TILE_ID_COPPER_ORE_MINE": "44",
    "INDUSTRY_TILE_ID_COPPER_SMELTER": "45",
    "INDUSTRY_TILE_ID_PAINT_FACTORY": "47",
    
    # TILE IDs for FOOD_INDUSTRIES_EXTENSION
    "INDUSTRY_TILE_ID_ANIMAL_FARM" : "54",
    "INDUSTRY_TILE_ID_BREWERY_1" : "48",
    "INDUSTRY_TILE_ID_BREWERY_2" : "49",
    "INDUSTRY_TILE_ID_DAIRY_1" : "50",
    "INDUSTRY_TILE_ID_DAIRY_2" : "51",
    "INDUSTRY_TILE_ID_FLOUR_MILL" : "52",
    "INDUSTRY_TILE_ID_STOCKYARD" : "53",    
    
    # TILE IDs for PACKAGING INDUSTRIES EXTENSION
    "INDUSTRY_TILE_ID_PACKAGING_PLANT" : "55",
    
    # TILE IDs for GLASS
    "INDUSTRY_TILE_ID_GLASS_WORKS" : "57",
    "INDUSTRY_TILE_ID_LIME_KILN" : "56",
    
    # TILE IDs for PAPER
    "INDUSTRY_TILE_ID_PAPER_MILL" : "58",
    "INDUSTRY_TILE_ID_PRINTING_WORKS" : "59",
    
    # TILE IDs for ORGANIC CHEMISTRY
    "INDUSTRY_TILE_ID_COAL_LIQUEFACTION_PLANT" : "63",
    "INDUSTRY_TILE_ID_OIL_REFINERY" : "60",
    "INDUSTRY_TILE_ID_PETROL_STATION" : "64",
    "INDUSTRY_TILE_ID_STEAMCRACKER_1" : "61",
    "INDUSTRY_TILE_ID_STEAMCRACKER_2" : "62",
    "INDUSTRY_TILE_ID_STEAMREFORMER" : "65",
    
    # TILE IDs for COKE SULPHUR
    "INDUSTRY_TILE_ID_COKE_OVEN_1" : "66",
    "INDUSTRY_TILE_ID_COKE_OVEN_2" : "67",
    "INDUSTRY_TILE_ID_ORE_SMELTER" : "68",
    "INDUSTRY_TILE_ID_ACID_PLANT_1" : "69",
    "INDUSTRY_TILE_ID_ACID_PLANT_2" : "70",
    
    # TILE IDs for AMMONIA
    "INDUSTRY_TILE_ID_AMMONIA_PLANT" : "72",
    "INDUSTRY_TILE_ID_CLEANING_PRODUCTS_FACTORY" : "74",
    "INDUSTRY_TILE_ID_CRYO_PLANT" : "71",
    "INDUSTRY_TILE_ID_SODA_PLANT" : "73",   

    # TILE IDs for FRUITS
    "INDUSTRY_TILE_ID_BIOREFINERY" : "77",
    "INDUSTRY_TILE_ID_FRUIT_PLANTATION_1" : "75",
    "INDUSTRY_TILE_ID_FRUIT_PLANTATION_2" : "76",
        
    # TTD sprite IDs
    "TTD_OILRIG_STATION_TILE": "24",
    "TTD_COPPER_ORE_MINE_ANIMATED_HEADGEAR":"2028",
    "TTD_COPPER_ORE_MINE_BIG_BUILDING" : "2034", #building stages 2034-2036
    "TTD_COPPER_ORE_MINE_HEADGEAR_CONSTRUCTION_1":"2026", # building stage 1
    "TTD_COPPER_ORE_MINE_HEADGEAR_CONSTRUCTION_2":"2027", # building stage 2
    "TTD_COPPER_ORE_MINE_SMALL_BUILDINGS" : "2037", #building stages 2037-2039
    "TTD_COPPER_ORE_MINE_WINCH_BUILDING_1": "2031", # building stages 2031-2033    
    "TTD_COPPER_ORE_MINE_WINCH_BUILDING_2": "2032", # building stages 2031-2033    
    "TTD_FENCE_X": "1301",
    "TTD_FENCE_Y": "1302",
    "TTD_GROUND_SPRITE_CONCRETE" : "1420",
    "TTD_GROUND_SPRITE_MUD_TRACK" : "2022", 
    "TTD_GROUND_SPRITE_BROWN":"3924",
    "TTD_GROUND_SPRITE_HALF_GREEN":"3943",
    "TTD_GROUND_SPRITE_MOSTLY_GREEN":"3962",
    "TTD_GROUND_SPRITE_PLANTATION":"4145",
    "TTD_SMOKE_SPRITE_DARK_SMALL" : "2040",
    "TTD_SMOKE_SPRITE_WHITE_BIG" : "3701",
    "TTD_SMOKE_SPRITE_WHITE_SMALL": "3079",
    "TTD_OIL_RIG_LEFT": "2096",
    "TTD_OIL_RIG_MIDDLE":"2097",
    "TTD_OIL_RIG_FRONT":"2098",
    "TTD_OIL_RIG_RIGHT":"2099",
    "TTD_OIL_RIG_CONSTRUCTION2_LEFT": "2100",
    "TTD_OIL_RIG_CONSTRUCTION2_MIDDLE":"2101",
    "TTD_OIL_RIG_CONSTRUCTION2_RIGHT":"2102",
    "TTD_OIL_RIG_CONSTRUCTION1_LEFT":"2103",
    "TTD_OIL_RIG_CONSTRUCTION1_MIDDLE": "2104",
    "TTD_OIL_RIG_CONSTRUCTION1_RIGHT":"2105",
    "TTD_OIL_WELL_GROUND":"2173",
    "TTD_OIL_WELL_PUMP":"2174",
    "TTD_POWER_PLANT_COOLING_TOWER":"2045",
    "TTD_POWER_PLANT_BUILDING":"2048",
    "TTD_POWER_PLANT_SMALL_BUILDING":"2051",
    "TTD_POWER_PLANT_SUBSTATION":"2054",
    "TTD_PRINTING_WORKS_TOP_LEFT":"2169",# building stages would be 2061,2065, but they have a different size
    "TTD_PRINTING_WORKS_TOP_RIGHT":"2170",# building stages would be 2062,2066, but they have a different size
    "TTD_PRINTING_WORKS_BOTTOM_LEFT":"2171",# building stages would be 2063,2067, but they have a different size
    "TTD_PRINTING_WORKS_BOTTOM_RIGHT":"2172",# building stages would be 2064,2068, but they have a different size
    "TTD_SAWMILL_SHED1":"2066", # building stages 2067-2069
    "TTD_SAWMILL_SHED2":"2060", # building stages 2061-2063
    "TTD_SAWMILL_SHED3":"2063", # building stages 2064-2066
    "TTD_SAWMILL_WOOD_STACK1":"2070",
    "TTD_SAWMILL_WOOD_STACK2":"2071",
    "TTD_TEMPERATE_TREE1":"1712",
    "TTD_TEMPERATE_TREE2":"1620",
    "TTD_TEMPERATE_TREE3":"1621",
    "TTD_TEMPERATE_TREE4":"1622",
    "TTD_TEMPERATE_TREE5":"1623",
    "TTD_TEMPERATE_DYING_TREE1":"1715",
    "TTD_TEMPERATE_DYING_TREE2":"1595",
    "TTD_TEMPERATE_DYING_TREE3":"1710",
    "TTD_TEMPERATE_DYING_TREE4":"1714",
    "TTD_SNOW_TREE":"1768",
    "TTD_SNOW_DYING_TREE1":"1771",
    "TTD_SNOW_DYING_TREE2":"1767",
    "TTD_SNOW_DYING_TREE3":"1766",
    "TTD_SNOW_DYING_TREE4":"1770",
    "TTD_TROPIC_TREE1":"1838",
    "TTD_TROPIC_TREE2":"1830",
    "TTD_TROPIC_TREE3":"1831",
    "TTD_TROPIC_TREE4":"1832",
    "TTD_TROPIC_DYING_TREE1":"1870",
    "TTD_TROPIC_DYING_TREE2":"1839",
    "TTD_TROPIC_DYING_TREE3":"1873",
    "TTD_TROPIC_DYING_TREE4":"1836",
    
    # registers used for STORE_TEMP / LOAD_TEMP
    "TEMP_REGISTER_MAXIMUM_PRIMARY_PRODUCTION" : "3",
    "TEMP_REGISTER_PRODUCTION_AMOUNT" : "4",
    "TEMP_REGISTER_FENCE_NE":"9",
    "TEMP_REGISTER_FENCE_NW":"10",
    "TEMP_REGISTER_FENCE_SE":"11",
    "TEMP_REGISTER_FENCE_SW":"12",
    "TEMP_REGISTER_IS_SNOW" : "13", 
    "TEMP_REGISTER_NO_TEMPERATE_TREE": "15",
    "TEMP_REGISTER_NO_SNOW_TREE": "16",
    "TEMP_REGISTER_NO_TROPIC_TREE": "17",
    "TEMP_REGISTER_TRANSPORTED_LAST_MONTH_PCT_CARGO0": "20",
    "TEMP_REGISTER_PRODUCTION_LAST_YEAR":"21",
    "TEMP_REGISTER_CURRENT_PRODUCTION_LEVEL": "30",
    "TEMP_REGISTER_CURRENT_PRODUCTION_AMOUNT": "31",
    "TEMP_REGISTER_POWER_DEMAND": "32",
    "TEMP_REGISTER_POWER_AVAILABLE": "33",
    "TEMP_REGISTER_PRODUCTION_RAW0" : "40",
    "TEMP_REGISTER_PRODUCTION_RAW1" : "41",
    "TEMP_REGISTER_PRODUCTION_RAW2" : "42",
    "TEMP_REGISTER_PRODUCTION_RAW3" : "43",
    "TEMP_REGISTER_PRODUCTION_RAW4" : "44",
    "TEMP_REGISTER_PRODUCTION_RAW5" : "45",
    "TEMP_REGISTER_PRODUCTION_RAW6" : "46",
    "TEMP_REGISTER_PRODUCTION_RAW7" : "47",
    "TEMP_REGISTER_PRODUCTION_RAW8" : "48",
    "TEMP_REGISTER_INCOMING_CARGO_WAITING0": "50",
    "TEMP_REGISTER_INCOMING_CARGO_WAITING1": "51",
    "TEMP_REGISTER_INCOMING_CARGO_WAITING2": "52",
    "TEMP_REGISTER_INCOMING_CARGO_WAITING3": "53", 
    "TEMP_REGISTER_INCOMING_CARGO_WAITING4": "54", 
    "TEMP_REGISTER_INCOMING_CARGO_WAITING5": "55", 
    "TEMP_REGISTER_INCOMING_CARGO_WAITING6": "56", 
    "TEMP_REGISTER_INCOMING_CARGO_WAITING7": "57", 
    "TEMP_REGISTER_INCOMING_CARGO_WAITING8": "58", 
    "TEMP_REGISTER_NUMBER_OF_WAITING_CARGOS": "60",
    "TEMP_REGISTER_INCOMING_CARGO_WAITING_MIN_AMOUNT" : "61",
    "TEMP_REGISTER_PARAM_PRODUCTION_SCALE":"70",
    "TEMP_REGISTER_TOWN_MIN_DISTANCE": "80",
    "TEMP_REGISTER_TOWN_MAX_DISTANCE": "81",
    "TEMP_REGISTER_GROUND_SPRITE":"100",
    "TEMP_REGISTER_HIDE_TILE_SNOW": "110",
    "TEMP_REGISTER_IS_CONSTRUCTION": "111",
    "TEMP_REGISTER_HIDE_TILE": "112",
    "TEMP_REGISTER_EXTRA_TEXT_ARG0": "256",
    "TEMP_REGISTER_EXTRA_TEXT_ARG1": "257",
    "TEMP_REGISTER_EXTRA_TEXT_ARG2": "258",
    "TEMP_REGISTER_EXTRA_TEXT_ARG3": "259",
    "TEMP_REGISTER_CB_RESULT_IND_PROD_SET_BY_0x100": "256",
    
    # registers used for STORE_PERM / LOAD_PERM
    "PERM_REGISTER_RESOURCES" : "1",
    "PERM_REGISTER_POWER_AVAILABLE" : "2",
    "PERM_REGISTER_POWER_DEMAND" : "3",
    "PERM_REGISTER_PRODUCTION_PERCENTAGE" : "4",
    "PERM_REGISTER_CITY_POWER_AVAILABLE": "5",
    "PERM_REGISTER_CITY_POWER_DEMAND": "6",
    "PERM_REGISTER_PRODUCTION_AMOUNT": "7",
    "PERM_REGISTER_MAXIMUM_PRODUCTION_AMOUNT": "8",
    "PERM_REGISTER_PREV_POWER_DEMAND": "9",
    "PERM_REGISTER_LAST_SERVED00": "10",
    "PERM_REGISTER_LAST_SERVED01": "11",
    "PERM_REGISTER_LAST_SERVED02": "12",
    "PERM_REGISTER_LAST_SERVED03": "13",
    "PERM_REGISTER_LAST_SERVED04": "14",
    "PERM_REGISTER_LAST_SERVED05": "15",
    "PERM_REGISTER_LAST_SERVED06": "16",
    "PERM_REGISTER_LAST_SERVED07": "17",
    "PERM_REGISTER_LAST_SERVED08": "18",
    "PERM_REGISTER_LAST_SERVED09": "19",
    "PERM_REGISTER_LAST_SERVED10": "20",
    "PERM_REGISTER_LAST_SERVED11": "21",
    
    "PERM_REGISTER_DBG_NUMBER_OF_WAITING_CARGOS": "30",
    "PERM_REGISTER_DBG_CURRENT_PRODUCTION_AMOUNT": "31",
    "PERM_REGISTER_DBG_PRODUCTION_SCALE": "32",
    "PERM_REGISTER_DBG_INCOMING_CARGO_WAITING0": "40",
    "PERM_REGISTER_DBG_INCOMING_CARGO_WAITING1": "41",
    "PERM_REGISTER_DBG_INCOMING_CARGO_WAITING2": "42",
    "PERM_REGISTER_DBG_INCOMING_CARGO_WAITING3": "43",
    "PERM_REGISTER_DBG_INCOMING_CARGO_WAITING4": "44",
    "PERM_REGISTER_DBG_INCOMING_CARGO_WAITING5": "45",
    "PERM_REGISTER_DBG_INCOMING_CARGO_WAITING6": "46",
    "PERM_REGISTER_DBG_INCOMING_CARGO_WAITING7": "47",
    "PERM_REGISTER_DBG_INCOMING_CARGO_WAITING8": "48",
    "PERM_REGISTER_DBG_PRODUCTION_RAW0": "50",
    "PERM_REGISTER_DBG_PRODUCTION_RAW1": "51",
    "PERM_REGISTER_DBG_PRODUCTION_RAW2": "52",
    "PERM_REGISTER_DBG_PRODUCTION_RAW3": "53",
    "PERM_REGISTER_DBG_PRODUCTION_RAW4": "54",
    "PERM_REGISTER_DBG_PRODUCTION_RAW5": "55",
    "PERM_REGISTER_DBG_PRODUCTION_RAW6": "56",
    "PERM_REGISTER_DBG_PRODUCTION_RAW7": "57",
    "PERM_REGISTER_DBG_PRODUCTION_RAW8": "58",
}