# This file defines a dictionary of constants that are simply replaced in pnml file (key is replaced by value)
# Used to make the code more readable by avoiding magic numbers
constants = {
    # CARGO IDs 0-14, Base Cargos
    "CARGO_ID_COAL": "1",
    "CARGO_ID_FISH": "10",
    "CARGO_ID_FOOD": "11",
    "CARGO_ID_GOODS": "5",
    "CARGO_ID_GRAIN": "6",
    "CARGO_ID_IRON_ORE": "8",
    "CARGO_ID_LIVESTOCK": "4",
    "CARGO_ID_MAIL":"2",
    "CARGO_ID_OIL": "3",
    "CARGO_ID_PASSENGERS":"0",
    "CARGO_ID_PLASTICS":"12",
    "CARGO_ID_STEEL": "9",
    "CARGO_ID_WOOD": "7",
    "CARGO_ID_TIMBER": "13",
    "CARGO_ID_VEHICLES": "14",
    
    # CARGO IDs BUILDING MATERIAL EXTENSION
    "CARGO_ID_LIMESTONE": "15",
    "CARGO_ID_SAND": "16",
    "CARGO_ID_CEMENT": "17",
    "CARGO_ID_BUILDING_MATERIALS": "18",
    
    # CARGO IDs TEXTILE INDUSTRIES EXTENSION
    "CARGO_ID_TEXTILES": "20",
    "CARGO_ID_WOOL": "19",
    
    # CARGO IDs ALUMINIUM EXTENSION
    "CARGO_ID_ALUMINIUM": "21",
    "CARGO_ID_BAUXITE": "22",
    
    # CARGO IDs BASIC INORGANIC CHEMISTRY EXTENSION
    "CARGO_ID_CHLORINE": "24",
    "CARGO_ID_HYDROGEN": "26",
    "CARGO_ID_LYE": "25",
    "CARGO_ID_SALT": "23",
    
    # CARGO IDs PAINTINGS INDUSTRIES
    "CARGO_ID_CARBON_BLACK": "29",
    "CARGO_ID_COPPER_ORE": "27",
    "CARGO_ID_COPPER": "28",
    "CARGO_ID_PAINT": "30",
    
    # CARGO IDs FOOD INDUSTRY
    "CARGO_ID_MILK": "31",
    
    # CARGO IDs PACKAGING INDUSTRY
    "CARGO_ID_PACKAGING" : "32",
    
    # CARGO IDs GLASS
    "CARGO_ID_GLASS": "34",
    "CARGO_ID_QUICKLIME": "33",
    
    # CARGO IDs PAPER
    "CARGO_ID_PAPER": "35",
    
    # CARGO IDs ORGANIC CHEMISTRY
    "CARGO_ID_ETHYLENE": "37",
    "CARGO_ID_NAPHTHA" : "36",    
    "CARGO_ID_PETROL" : "38",
    
    # CARGO IDs COKE SULPHUR
    "CARGO_ID_ACID" : "42",
    "CARGO_ID_COKE" : "39",
    "CARGO_ID_PYRITE_ORE" : "40",
    "CARGO_ID_SULPHUR" : "41",
    
    # CARGO IDs AMMONIA
    "CARGO_ID_AMMONIA" : "45",
    "CARGO_ID_N2" : "44",
    "CARGO_ID_O2" : "43",
    "CARGO_ID_SODA" : "46",
    
    # CARGO IDs FRUITS
    "CARGO_ID_BIOMASS" : "48",
    "CARGO_ID_FRUITS" : "47",
    
    # CARGO IDs METALLURGY
    "CARGO_ID_MACHINE_PARTS" : "49",
    "CARGO_ID_METAL_SHEETS" : "50",
    "CARGO_ID_METAL_WIRE" : "51",
    
    # CARGO_IDs RECYCLING
    "CARGO_ID_RECYCLABLES" : "53",
    "CARGO_ID_SCRAP_METAL" : "52",  

    # CARGO IDs VEHICLE
    "CARGO_ID_RUBBER" : "54",
    "CARGO_ID_TYRE" : "56",
    "CARGO_ID_VEHICLE_BODY" : "58",
    "CARGO_ID_VEHICLE_ENGINE" : "57",
    "CARGO_ID_VEHICLE_PARTS" : "59",
    "CARGO_ID_ZINC" : "55",   

    # CARGO IDs PRODUCTION BOOST
    "CARGO_ID_AMMONIUM_NITRATE" : "62",
    "CARGO_ID_EXPLOSIVES" : "60",
    "CARGO_ID_FERTILIZER" : "61",
    "CARGO_ID_POTASH" : "63",

    # INDUSTRY IDS 0-20 (with gaps): Base Industries
    "INDUSTRY_ID_BUILDERS_YARD":"17",
    "INDUSTRY_ID_COAL_MINE": "0",
    "INDUSTRY_ID_DEPARTMENT_STORE": "15",
    "INDUSTRY_ID_FURNITURE_FACTORY":"6",
    "INDUSTRY_ID_FARM":"9",
    "INDUSTRY_ID_FISHING_GROUNDS":"10",
    "INDUSTRY_ID_FOOD_PROCESSOR": "12",
    "INDUSTRY_ID_FOREST":"3",
    "INDUSTRY_ID_GENERAL_STORE":"14",
    "INDUSTRY_ID_HOTEL":"19",
    "INDUSTRY_ID_INTEGRATED_STEEL_MILL":"8",
    "INDUSTRY_ID_IRON_ORE_MINE":"18",
    "INDUSTRY_ID_OIL_RIG":"5",
    "INDUSTRY_ID_OIL_WELL":"11",
    "INDUSTRY_ID_PLASTICS_PLANT":"4",
    "INDUSTRY_ID_PORT":"20",
    "INDUSTRY_ID_POWER_PLANT": "1",
    "INDUSTRY_ID_SAWMILL":"2",
    "INDUSTRY_ID_VEHICLE_DISTRIBUTOR":"16",
    "INDUSTRY_ID_VEHICLE_FACTORY":"13",
    
    # Building Material Extension
    "INDUSTRY_ID_BRICK_WORKS": "24",
    "INDUSTRY_ID_LIMESTONE_MINE": "21",
    "INDUSTRY_ID_SANDPIT": "22",
    "INDUSTRY_ID_CEMENT_PLANT": "23",
    
    # Textile Industries Extension
    "INDUSTRY_ID_CLOTHING_PLANT": "26",
    "INDUSTRY_ID_TEXTILE_MILL": "25",
    
    # Aluminium Extension
    "INDUSTRY_ID_ALUMINIUM_PLANT": "27",
    
    # Basic Inorganic Chemistry Extension
    "INDUSTRY_ID_CHLOR_ALKALI_PLANT": "29",
    "INDUSTRY_ID_PHARMACEUTICAL_PLANT": "30",
    "INDUSTRY_ID_SALT_MINE": "28",
    
    # Paint Industries Extension
    "INDUSTRY_ID_CARBON_BLACK_PLANT": "33",
    "INDUSTRY_ID_COPPER_ORE_MINE": "31",
    "INDUSTRY_ID_COPPER_SMELTER": "32",
    "INDUSTRY_ID_PAINT_FACTORY": "34",
    
    # Food Industries Extension
    "INDUSTRY_ID_ANIMAL_FARM" : "39",
    "INDUSTRY_ID_BREWERY" : "35",
    "INDUSTRY_ID_DAIRY" : "38",
    "INDUSTRY_ID_FLOUR_MILL" : "36",
    "INDUSTRY_ID_STOCKYARD" : "37",
    
    # Packaging Industries Extension
    "INDUSTRY_ID_PACKAGING_PLANT" : "40",
    
    # Glass Extension
    "INDUSTRY_ID_GLASS_WORKS" : "42",
    "INDUSTRY_ID_LIME_KILN" : "41",
    
    # Paper Extension
    "INDUSTRY_ID_PAPER_MILL" : "43",
    "INDUSTRY_ID_PRINTING_WORKS" : "7", # original ID of the builtin printing works
    
    # Organic Chemistry Extension
    "INDUSTRY_ID_COAL_LIQUEFACTION_PLANT" : "47",
    "INDUSTRY_ID_OIL_REFINERY" : "44",
    "INDUSTRY_ID_PETROL_STATION" : "48",
    "INDUSTRY_ID_STEAMCRACKER" : "46",
    "INDUSTRY_ID_STEAMREFORMER" : "45",  

    # Coke Sulphur Extension
    "INDUSTRY_ID_ACID_PLANT": "50",
    "INDUSTRY_ID_COKE_OVEN": "49",
    "INDUSTRY_ID_ORE_SMELTER": "51",
    
    # Ammonia Extension
    "INDUSTRY_ID_AMMONIA_PLANT": "53",
    "INDUSTRY_ID_CLEANING_PRODUCTS_FACTORY": "55",
    "INDUSTRY_ID_CRYO_PLANT": "52",    
    "INDUSTRY_ID_SODA_PLANT": "54",
    
    # Fruits Extension
    "INDUSTRY_ID_FRUIT_PLANTATION":"56",
    "INDUSTRY_ID_BIOREFINERY":"57",
    
    # Metallurgy Extension
    "INDUSTRY_ID_APPLIANCE_FACTORY":"61",
    "INDUSTRY_ID_FOUNDRY_FORGE":"58",
    "INDUSTRY_ID_SHEET_MILL":"59",
    "INDUSTRY_ID_WIRE_MILL":"60",
    
    # Recycling Extension
    "INDUSTRY_ID_RECYCLING_DEPOT":"63",
    "INDUSTRY_ID_SCRAP_YARD":"62",
    
    # Vehicles Extension
    "INDUSTRY_ID_SYNTHETIC_RUBBER_PLANT":"64",
    "INDUSTRY_ID_TYRE_PLANT":"65",
    "INDUSTRY_ID_VEHICLE_PARTS_PLANT":"66",
    "INDUSTRY_ID_VEHICLE_ENGINE_PLANT":"67",
    "INDUSTRY_ID_VEHICLE_BODY_PLANT":"68",
    
    # Production Boost
    "INDUSTRY_ID_FERTILIZER_PLANT":"70",
    "INDUSTRY_ID_POTASH_MINE":"69",
    "INDUSTRY_ID_AMMONIUM_NITRATE_PLANT":"71",
    "INDUSTRY_ID_EXPLOSIVES_FACTORY":"72",
    
    # INDUSTRY TILE IDs for Base Industries
    "INDUSTRY_TILE_ID_BUILDERS_YARD":"22",
    "INDUSTRY_TILE_ID_COAL_MINE_1": "0",
    "INDUSTRY_TILE_ID_COAL_MINE_2": "1",
    "INDUSTRY_TILE_ID_DEPARTMENT_STORE":"20",
    "INDUSTRY_TILE_ID_FURNITURE_FACTORY_1":"15",
    "INDUSTRY_TILE_ID_FURNITURE_FACTORY_2":"93",
    "INDUSTRY_TILE_ID_FARM":"14",
    "INDUSTRY_TILE_ID_FISHING_GROUNDS":"16",
    "INDUSTRY_TILE_ID_FOOD_PROCESSOR_1": "17",
    "INDUSTRY_TILE_ID_FOOD_PROCESSOR_2": "90",
    "INDUSTRY_TILE_ID_FOOD_PROCESSOR_3": "91",
    "INDUSTRY_TILE_ID_FOOD_PROCESSOR_4": "92",
    "INDUSTRY_TILE_ID_FOREST_1":"11",
    "INDUSTRY_TILE_ID_FOREST_2":"12",
    "INDUSTRY_TILE_ID_GENERAL_STORE":"19",
    "INDUSTRY_TILE_ID_HOTEL":"23",
    "INDUSTRY_TILE_ID_INTEGRATED_STEEL_MILL_1":"8",
    "INDUSTRY_TILE_ID_INTEGRATED_STEEL_MILL_2":"9",
    "INDUSTRY_TILE_ID_INTEGRATED_STEEL_MILL_3":"96",
    "INDUSTRY_TILE_ID_INTEGRATED_STEEL_MILL_4":"97",
    "INDUSTRY_TILE_ID_INTEGRATED_STEEL_MILL_5":"98",
    "INDUSTRY_TILE_ID_INTEGRATED_STEEL_MILL_6":"99",
    "INDUSTRY_TILE_ID_IRON_ORE_MINE_1": "5",
    "INDUSTRY_TILE_ID_IRON_ORE_MINE_2": "6",
    "INDUSTRY_TILE_ID_IRON_ORE_MINE_3": "7",
    "INDUSTRY_TILE_ID_PLASTICS_PLANT_1":"10",
    "INDUSTRY_TILE_ID_PLASTICS_PLANT_2":"109",
    "INDUSTRY_TILE_ID_PLASTICS_PLANT_3":"110",
    "INDUSTRY_TILE_ID_PLASTICS_PLANT_4":"111",
    "INDUSTRY_TILE_ID_OIL_RIG":"24",
    "INDUSTRY_TILE_ID_OIL_WELL_ANIM": "4",
    "INDUSTRY_TILE_ID_OIL_WELL":"3",
    "INDUSTRY_TILE_ID_PORT_1":"25",
    "INDUSTRY_TILE_ID_PORT_2":"26",
    "INDUSTRY_TILE_ID_POWER_PLANT_ANIM":"2",
    "INDUSTRY_TILE_ID_SAWMILL_1":"13",
    "INDUSTRY_TILE_ID_VEHICLE_DISTRIBUTOR":"21",
    "INDUSTRY_TILE_ID_VEHICLE_FACTORY_1":"18",
    "INDUSTRY_TILE_ID_VEHICLE_FACTORY_2":"119",
    "INDUSTRY_TILE_ID_VEHICLE_FACTORY_3":"120",
    "INDUSTRY_TILE_ID_VEHICLE_FACTORY_4":"121",
    "INDUSTRY_TILE_ID_VEHICLE_FACTORY_5":"122",
    "INDUSTRY_TILE_ID_VEHICLE_FACTORY_6":"123",
    "INDUSTRY_TILE_ID_VEHICLE_FACTORY_7":"124",

    # TILE IDs for BUILDING MATERIAL EXTENSION
    "INDUSTRY_TILE_ID_BRICK_WORKS":"33",
    "INDUSTRY_TILE_ID_CEMENT_PLANT":"32",
    "INDUSTRY_TILE_ID_LIMESTONE_MINE_1": "27",
    "INDUSTRY_TILE_ID_LIMESTONE_MINE_2": "28",
    "INDUSTRY_TILE_ID_LIMESTONE_MINE_3": "29",
    "INDUSTRY_TILE_ID_SANDPIT_1":"30",
    "INDUSTRY_TILE_ID_SANDPIT_2":"31",
    
    # TILE IDs for TEXTILE INDUSTRIES EXTENSION
    "INDUSTRY_TILE_ID_TEXTILE_MILL": "34",
    "INDUSTRY_TILE_ID_CLOTHING_PLANT": "35",
    
    # TILE IDs for ALUMINIUM EXTENSION
    "INDUSTRY_TILE_ID_ALUMINIUM_PLANT": "36",
    
    # TILE IDs for BASIC_INORGANIC_CHEMISTRY_EXTENSION
    "INDUSTRY_TILE_ID_CHLOR_ALKALI_PLANT_1": "40",
    "INDUSTRY_TILE_ID_CHLOR_ALKALI_PLANT_2": "41",
    "INDUSTRY_TILE_ID_PHARMACEUTICAL_PLANT_1": "42",
    "INDUSTRY_TILE_ID_PHARMACEUTICAL_PLANT_2": "43",
    "INDUSTRY_TILE_ID_PHARMACEUTICAL_PLANT_3": "106",
    "INDUSTRY_TILE_ID_PHARMACEUTICAL_PLANT_4": "107",
    "INDUSTRY_TILE_ID_PHARMACEUTICAL_PLANT_5": "108",
    "INDUSTRY_TILE_ID_SALT_MINE_1": "37",
    "INDUSTRY_TILE_ID_SALT_MINE_2": "38",
    "INDUSTRY_TILE_ID_SALT_MINE_3": "39",
    
    # TILE IDs for PAINT_INDUSTRIES EXTENSION
    "INDUSTRY_TILE_ID_CARBON_BLACK_PLANT": "46",
    "INDUSTRY_TILE_ID_COPPER_ORE_MINE": "44",
    "INDUSTRY_TILE_ID_COPPER_SMELTER_1": "45",
    "INDUSTRY_TILE_ID_COPPER_SMELTER_2": "129",
    "INDUSTRY_TILE_ID_PAINT_FACTORY_1": "47",
    "INDUSTRY_TILE_ID_PAINT_FACTORY_2": "103",
    "INDUSTRY_TILE_ID_PAINT_FACTORY_3": "104",
    
    # TILE IDs for FOOD_INDUSTRIES_EXTENSION
    "INDUSTRY_TILE_ID_ANIMAL_FARM" : "54",
    "INDUSTRY_TILE_ID_BREWERY_1" : "48",
    "INDUSTRY_TILE_ID_BREWERY_2" : "49",
    "INDUSTRY_TILE_ID_DAIRY_1" : "50",
    "INDUSTRY_TILE_ID_DAIRY_2" : "51",
    "INDUSTRY_TILE_ID_FLOUR_MILL" : "52",
    "INDUSTRY_TILE_ID_STOCKYARD" : "53",    
    
    # TILE IDs for PACKAGING INDUSTRIES EXTENSION
    "INDUSTRY_TILE_ID_PACKAGING_PLANT_1" : "55",
    "INDUSTRY_TILE_ID_PACKAGING_PLANT_2" : "100",
    "INDUSTRY_TILE_ID_PACKAGING_PLANT_3" : "101",
    "INDUSTRY_TILE_ID_PACKAGING_PLANT_4" : "102",
    
    # TILE IDs for GLASS
    "INDUSTRY_TILE_ID_GLASS_WORKS_1" : "57",
    "INDUSTRY_TILE_ID_GLASS_WORKS_2" : "94",
    "INDUSTRY_TILE_ID_GLASS_WORKS_3" : "95",
    "INDUSTRY_TILE_ID_GLASS_WORKS_4" : "141",
    "INDUSTRY_TILE_ID_LIME_KILN" : "56",
    
    # TILE IDs for PAPER
    "INDUSTRY_TILE_ID_PAPER_MILL_1" : "58",
    "INDUSTRY_TILE_ID_PAPER_MILL_2" : "105",
    "INDUSTRY_TILE_ID_PRINTING_WORKS" : "59",
    
    # TILE IDs for ORGANIC CHEMISTRY
    "INDUSTRY_TILE_ID_COAL_LIQUEFACTION_PLANT" : "63",
    "INDUSTRY_TILE_ID_OIL_REFINERY" : "60",
    "INDUSTRY_TILE_ID_PETROL_STATION" : "64",
    "INDUSTRY_TILE_ID_STEAMCRACKER_1" : "61",
    "INDUSTRY_TILE_ID_STEAMCRACKER_2" : "62",
    "INDUSTRY_TILE_ID_STEAMREFORMER" : "65",
    
    # TILE IDs for COKE SULPHUR
    "INDUSTRY_TILE_ID_COKE_OVEN_1" : "66",
    "INDUSTRY_TILE_ID_COKE_OVEN_2" : "67",
    "INDUSTRY_TILE_ID_ORE_SMELTER" : "68",
    "INDUSTRY_TILE_ID_ACID_PLANT_1" : "69",
    "INDUSTRY_TILE_ID_ACID_PLANT_2" : "70",
    
    # TILE IDs for AMMONIA
    "INDUSTRY_TILE_ID_AMMONIA_PLANT" : "72",
    "INDUSTRY_TILE_ID_CLEANING_PRODUCTS_FACTORY_1" : "74",
    "INDUSTRY_TILE_ID_CLEANING_PRODUCTS_FACTORY_2" : "130",
    "INDUSTRY_TILE_ID_CLEANING_PRODUCTS_FACTORY_3" : "142",
    "INDUSTRY_TILE_ID_CRYO_PLANT" : "71",
    "INDUSTRY_TILE_ID_SODA_PLANT" : "73",   

    # TILE IDs for FRUITS
    "INDUSTRY_TILE_ID_BIOREFINERY" : "77",
    "INDUSTRY_TILE_ID_FRUIT_PLANTATION_1" : "75",
    "INDUSTRY_TILE_ID_FRUIT_PLANTATION_2" : "76",
    
    # TILE_IDs for METALLURGY
    "INDUSTRY_TILE_ID_APPLIANCE_FACTORY_1": "81",
    "INDUSTRY_TILE_ID_APPLIANCE_FACTORY_2": "89",
    "INDUSTRY_TILE_ID_FOUNDRY_FORGE" : "78",
    "INDUSTRY_TILE_ID_SHEET_MILL_1" : "79",
    "INDUSTRY_TILE_ID_SHEET_MILL_2" : "112",
    "INDUSTRY_TILE_ID_WIRE_MILL_1": "80",
    "INDUSTRY_TILE_ID_WIRE_MILL_2": "128",
    
    # TILE_IDs for RECYCLING
    "INDUSTRY_TILE_ID_RECYCLING_DEPOT" : "83",
    "INDUSTRY_TILE_ID_SCRAP_YARD" : "82",
    
    # TILE_IDs for VEHICLES
    "INDUSTRY_TILE_ID_SYNTHETIC_RUBBER_PLANT_1" : "84",
    "INDUSTRY_TILE_ID_SYNTHETIC_RUBBER_PLANT_2" : "113",
    "INDUSTRY_TILE_ID_TYRE_PLANT" : "85",
    "INDUSTRY_TILE_ID_VEHICLE_PARTS_PLANT_1":"86",
    "INDUSTRY_TILE_ID_VEHICLE_PARTS_PLANT_2":"125",
    "INDUSTRY_TILE_ID_VEHICLE_PARTS_PLANT_3":"126",
    "INDUSTRY_TILE_ID_VEHICLE_PARTS_PLANT_4":"127",
    "INDUSTRY_TILE_ID_VEHICLE_ENGINE_PLANT_1":"87",
    "INDUSTRY_TILE_ID_VEHICLE_ENGINE_PLANT_2":"118",
    "INDUSTRY_TILE_ID_VEHICLE_BODY_PLANT_1":"88",
    "INDUSTRY_TILE_ID_VEHICLE_BODY_PLANT_2":"114",
    "INDUSTRY_TILE_ID_VEHICLE_BODY_PLANT_3":"115",
    "INDUSTRY_TILE_ID_VEHICLE_BODY_PLANT_4":"116",
    "INDUSTRY_TILE_ID_VEHICLE_BODY_PLANT_5":"117",
    
    # TILE IDs for PRODUCTION BOOST
    "INDUSTRY_TILE_ID_POTASH_MINE_1":"131",
    "INDUSTRY_TILE_ID_POTASH_MINE_2":"132",
    "INDUSTRY_TILE_ID_POTASH_MINE_3":"133",
    "INDUSTRY_TILE_ID_AMMONIUM_NITRATE_PLANT_1":"134",
    "INDUSTRY_TILE_ID_AMMONIUM_NITRATE_PLANT_2":"135",
    "INDUSTRY_TILE_ID_EXPLOSIVES_FACTORY_1":"136",
    "INDUSTRY_TILE_ID_EXPLOSIVES_FACTORY_2":"137",
    "INDUSTRY_TILE_ID_FERTILIZER_PLANT_1":"138",
    "INDUSTRY_TILE_ID_FERTILIZER_PLANT_2":"139",
    "INDUSTRY_TILE_ID_FERTILIZER_PLANT_3":"140",
        
    # TTD sprite IDs
    "TTD_OILRIG_STATION_TILE": "24",
    "TTD_COPPER_ORE_MINE_ANIMATED_HEADGEAR":"2028",
    "TTD_COPPER_ORE_MINE_BIG_BUILDING" : "2034", #building stages 2034-2036
    "TTD_COPPER_ORE_MINE_HEADGEAR_CONSTRUCTION_1":"2026", # building stage 1
    "TTD_COPPER_ORE_MINE_HEADGEAR_CONSTRUCTION_2":"2027", # building stage 2
    "TTD_COPPER_ORE_MINE_SMALL_BUILDINGS" : "2037", #building stages 2037-2039
    "TTD_COPPER_ORE_MINE_WINCH_BUILDING_1": "2031", # building stages 2031-2033    
    "TTD_COPPER_ORE_MINE_WINCH_BUILDING_2": "2032", # building stages 2031-2033    
    "TTD_FENCE_X": "1301",
    "TTD_FENCE_Y": "1302",
    "TTD_GROUND_SPRITE_CONCRETE" : "1420",
    "TTD_GROUND_SPRITE_MUD_TRACK" : "2022", 
    "TTD_GROUND_SPRITE_BROWN":"3924",
    "TTD_GROUND_SPRITE_HALF_GREEN":"3943",
    "TTD_GROUND_SPRITE_MOSTLY_GREEN":"3962",
    "TTD_GROUND_SPRITE_PLANTATION":"4145",
    "TTD_SMOKE_SPRITE_DARK_SMALL" : "2040",
    "TTD_SMOKE_SPRITE_WHITE_BIG" : "3701",
    "TTD_SMOKE_SPRITE_WHITE_SMALL": "3079",
    "TTD_OIL_RIG_LEFT": "2096",
    "TTD_OIL_RIG_MIDDLE":"2097",
    "TTD_OIL_RIG_FRONT":"2098",
    "TTD_OIL_RIG_RIGHT":"2099",
    "TTD_OIL_RIG_CONSTRUCTION2_LEFT": "2100",
    "TTD_OIL_RIG_CONSTRUCTION2_MIDDLE":"2101",
    "TTD_OIL_RIG_CONSTRUCTION2_RIGHT":"2102",
    "TTD_OIL_RIG_CONSTRUCTION1_LEFT":"2103",
    "TTD_OIL_RIG_CONSTRUCTION1_MIDDLE": "2104",
    "TTD_OIL_RIG_CONSTRUCTION1_RIGHT":"2105",
    "TTD_OIL_WELL_GROUND":"2173",
    "TTD_OIL_WELL_PUMP":"2174",
    "TTD_POWER_PLANT_COOLING_TOWER":"2045",
    "TTD_POWER_PLANT_BUILDING":"2048",
    "TTD_POWER_PLANT_SMALL_BUILDING":"2051",
    "TTD_POWER_PLANT_SUBSTATION":"2054",
    "TTD_PRINTING_WORKS_TOP_LEFT":"2169",# building stages would be 2061,2065, but they have a different size
    "TTD_PRINTING_WORKS_TOP_RIGHT":"2170",# building stages would be 2062,2066, but they have a different size
    "TTD_PRINTING_WORKS_BOTTOM_LEFT":"2171",# building stages would be 2063,2067, but they have a different size
    "TTD_PRINTING_WORKS_BOTTOM_RIGHT":"2172",# building stages would be 2064,2068, but they have a different size
    "TTD_SAWMILL_SHED1":"2066", # building stages 2067-2069
    "TTD_SAWMILL_SHED2":"2060", # building stages 2061-2063
    "TTD_SAWMILL_SHED3":"2063", # building stages 2064-2066
    "TTD_SAWMILL_WOOD_STACK1":"2070",
    "TTD_SAWMILL_WOOD_STACK2":"2071",
    "TTD_TEMPERATE_TREE1":"1712",
    "TTD_TEMPERATE_TREE2":"1620",
    "TTD_TEMPERATE_TREE3":"1621",
    "TTD_TEMPERATE_TREE4":"1622",
    "TTD_TEMPERATE_TREE5":"1623",
    "TTD_TEMPERATE_DYING_TREE1":"1715",
    "TTD_TEMPERATE_DYING_TREE2":"1595",
    "TTD_TEMPERATE_DYING_TREE3":"1710",
    "TTD_TEMPERATE_DYING_TREE4":"1714",
    "TTD_SNOW_TREE":"1768",
    "TTD_SNOW_DYING_TREE1":"1771",
    "TTD_SNOW_DYING_TREE2":"1767",
    "TTD_SNOW_DYING_TREE3":"1766",
    "TTD_SNOW_DYING_TREE4":"1770",
    "TTD_TROPIC_TREE1":"1838",
    "TTD_TROPIC_TREE2":"1830",
    "TTD_TROPIC_TREE3":"1831",
    "TTD_TROPIC_TREE4":"1832",
    "TTD_TROPIC_DYING_TREE1":"1870",
    "TTD_TROPIC_DYING_TREE2":"1839",
    "TTD_TROPIC_DYING_TREE3":"1873",
    "TTD_TROPIC_DYING_TREE4":"1836",
    
    # registers used for STORE_TEMP / LOAD_TEMP
    "TEMP_REGISTER_MAXIMUM_PRODUCTION" : "3",                   # Maximum production of a industry, depending on the settings and current game year
    "TEMP_REGISTER_PRODUCTION_AMOUNT" : "4",                    # Actual production in this production cycle after calculating limits and stuff
    "TEMP_REGISTER_TMP":"5",                                    # really temporary data, only to be used within a single switch
    "TEMP_REGISTER_TRANSPORTED_LAST_MONTH_PCT_CARGO0": "20",    # Percentage of cargo transported, needed when calculating production increase for primary industry
    
    "TEMP_REGISTER_RESOURCES":"22",                             # Resources of primary industry
    
    # registers used for stockpile handling
    "TEMP_REGISTER_STOCKPILE_FULL0":"24",                      
    "TEMP_REGISTER_STOCKPILE_FULL1":"25",
    "TEMP_REGISTER_STOCKPILE_FULL2":"26",
    
    # registers used for electricity-related industries
    "TEMP_REGISTER_POWER_DEMAND": "32",
    "TEMP_REGISTER_POWER_AVAILABLE": "33",
    
    # production values per raw material
    "TEMP_REGISTER_PRODUCTION_RAW0" : "40",
    "TEMP_REGISTER_PRODUCTION_RAW1" : "41",
    "TEMP_REGISTER_PRODUCTION_RAW2" : "42",
    "TEMP_REGISTER_PRODUCTION_RAW3" : "43",
    "TEMP_REGISTER_PRODUCTION_RAW4" : "44",
    "TEMP_REGISTER_PRODUCTION_RAW5" : "45",
    "TEMP_REGISTER_PRODUCTION_RAW6" : "46",
    "TEMP_REGISTER_PRODUCTION_RAW7" : "47",
    "TEMP_REGISTER_PRODUCTION_RAW8" : "48",
    # amount of incoming cargo waiting
    "TEMP_REGISTER_INCOMING_CARGO_WAITING0": "50",
    "TEMP_REGISTER_INCOMING_CARGO_WAITING1": "51",
    "TEMP_REGISTER_INCOMING_CARGO_WAITING2": "52",
    "TEMP_REGISTER_INCOMING_CARGO_WAITING3": "53", 
    "TEMP_REGISTER_INCOMING_CARGO_WAITING4": "54", 
    "TEMP_REGISTER_INCOMING_CARGO_WAITING5": "55", 
    "TEMP_REGISTER_INCOMING_CARGO_WAITING6": "56", 
    "TEMP_REGISTER_INCOMING_CARGO_WAITING7": "57", 
    "TEMP_REGISTER_INCOMING_CARGO_WAITING8": "58", 
    "TEMP_REGISTER_NUMBER_OF_WAITING_CARGOS": "59",
    "TEMP_REGISTER_INCOMING_OPT_CARGO_WAITING0": "60",
    "TEMP_REGISTER_INCOMING_OPT_CARGO_WAITING1": "61",
    "TEMP_REGISTER_INCOMING_OPT_CARGO_WAITING2": "62",
    "TEMP_REGISTER_INCOMING_OPT_CARGO_WAITING3": "63", 
    "TEMP_REGISTER_INCOMING_OPT_CARGO_WAITING4": "64", 
    "TEMP_REGISTER_INCOMING_OPT_CARGO_WAITING5": "65", 
    "TEMP_REGISTER_INCOMING_OPT_CARGO_WAITING6": "66", 
    "TEMP_REGISTER_INCOMING_OPT_CARGO_WAITING7": "67", 
    "TEMP_REGISTER_INCOMING_OPT_CARGO_WAITING8": "68", 
    "TEMP_REGISTER_NUMBER_OF_WAITING_OPT_CARGOS": "69",
    
    "TEMP_REGISTER_PRODUCTIVITY_SCALE":"70",
    "TEMP_REGISTER_PRODUCT_1":"71",
    "TEMP_REGISTER_PRODUCT_2":"72",
    "TEMP_REGISTER_PRODUCT_3":"73",
    "TEMP_REGISTER_PRODUCT_4":"74",
    "TEMP_REGISTER_PRODUCT_5":"75",
    "TEMP_REGISTER_PRODUCT_6":"76",
    
    # values needed when placing an industry
    "TEMP_REGISTER_TOWN_MIN_DISTANCE": "80",
    "TEMP_REGISTER_TOWN_MAX_DISTANCE": "81",
    "TEMP_REGISTER_NUMBER_OF_INDUSTRIES":"82",
    
    # values needed when drawing sprites
    "TEMP_REGISTER_FENCE_NE":"90",
    "TEMP_REGISTER_FENCE_NW":"91",
    "TEMP_REGISTER_FENCE_SE":"92",
    "TEMP_REGISTER_FENCE_SW":"93",
    "TEMP_REGISTER_IS_SNOW" : "94", 
    "TEMP_REGISTER_NO_TEMPERATE_TREE": "95",
    "TEMP_REGISTER_NO_SNOW_TREE": "96",
    "TEMP_REGISTER_NO_TROPIC_TREE": "97",
    "TEMP_REGISTER_GROUND_SPRITE":"98",
    "TEMP_REGISTER_HIDE_TILE_SNOW": "99",
    "TEMP_REGISTER_HIDE_TILE": "100",       # must be below TEMP_REGISTER_HIDE_TILE_SNOW to make the replacing work correctly!
    "TEMP_REGISTER_IS_CONSTRUCTION": "101",    
    
    # REGISTERS numbered by the standard for creating texts and CB results
    "TEMP_REGISTER_EXTRA_TEXT_ARG0": "256",
    "TEMP_REGISTER_EXTRA_TEXT_ARG1": "257",
    "TEMP_REGISTER_EXTRA_TEXT_ARG2": "258",
    "TEMP_REGISTER_EXTRA_TEXT_ARG3": "259",
    "TEMP_REGISTER_CB_RESULT_IND_PROD_SET_BY_0x100": "256",
    
    # registers used for STORE_PERM / LOAD_PERM
    "PERM_REGISTER_RESOURCES" : "1",                    # amount of resources for extractive industry
    
    # related to industries requiring electricity
    "PERM_REGISTER_POWER_DEMAND" : "2",                 # power demand of industry to make it produce at 100%
    "PERM_REGISTER_CITY_POWER_AVAILABLE": "3",          # power available in city for industrie
    "PERM_REGISTER_CITY_POWER_DEMAND": "4",             # total power demand for city as sum of industries
    "PERM_REGISTER_PREV_POWER_DEMAND": "5",             # As PERM_REGISTER_POWER_DEMAND is reset every production cycle, keep track of last total demand to show it in industry window of power plant

    "PERM_REGISTER_NUMBER_OF_OPTIONAL_CARGOS" : "6",
    "PERM_REGISTER_PRODUCTION_AMOUNT0": "7",            # Production amount for current production cycle after calculating limits due to electricity/optional cargos
    "PERM_REGISTER_PRODUCTION_AMOUNT1": "8",
    "PERM_REGISTER_PRODUCTION_AMOUNT2": "9",
    "PERM_REGISTER_PRODUCTION_AMOUNT3": "10",
    "PERM_REGISTER_PRODUCTION_AMOUNT4": "11",
    "PERM_REGISTER_PRODUCTION_AMOUNT5": "12",
    "PERM_REGISTER_MAXIMUM_PRODUCTION_AMOUNT0": "13",    # Maximum possible production before limits due to electricy/optional cargo are calculated
    "PERM_REGISTER_MAXIMUM_PRODUCTION_AMOUNT1": "14",
    "PERM_REGISTER_MAXIMUM_PRODUCTION_AMOUNT2": "15",
    "PERM_REGISTER_MAXIMUM_PRODUCTION_AMOUNT3": "16",
    "PERM_REGISTER_MAXIMUM_PRODUCTION_AMOUNT4": "17",
    "PERM_REGISTER_MAXIMUM_PRODUCTION_AMOUNT5": "18",
    
    
    # track whether industry was used over last 12 months
    "PERM_REGISTER_LAST_SERVED00": "20",                
    "PERM_REGISTER_LAST_SERVED01": "21",                
    "PERM_REGISTER_LAST_SERVED02": "22",
    "PERM_REGISTER_LAST_SERVED03": "23",
    "PERM_REGISTER_LAST_SERVED04": "24",
    "PERM_REGISTER_LAST_SERVED05": "25",
    "PERM_REGISTER_LAST_SERVED06": "26",
    "PERM_REGISTER_LAST_SERVED07": "27",
    "PERM_REGISTER_LAST_SERVED08": "28",
    "PERM_REGISTER_LAST_SERVED09": "29",
    "PERM_REGISTER_LAST_SERVED10": "30",
    "PERM_REGISTER_LAST_SERVED11": "31",
    
    # Used for debugging production
    "PERM_REGISTER_DBG_NUMBER_OF_WAITING_CARGOS": "40",
    "PERM_REGISTER_DBG_CURRENT_PRODUCTION_AMOUNT": "41",
    "PERM_REGISTER_DBG_PRODUCTION_SCALE": "42",
    "PERM_REGISTER_DBG_INCOMING_CARGO_WAITING0": "50",
    "PERM_REGISTER_DBG_INCOMING_CARGO_WAITING1": "51",
    "PERM_REGISTER_DBG_INCOMING_CARGO_WAITING2": "52",
    "PERM_REGISTER_DBG_INCOMING_CARGO_WAITING3": "53",
    "PERM_REGISTER_DBG_INCOMING_CARGO_WAITING4": "54",
    "PERM_REGISTER_DBG_INCOMING_CARGO_WAITING5": "55",
    "PERM_REGISTER_DBG_INCOMING_CARGO_WAITING6": "56",
    "PERM_REGISTER_DBG_INCOMING_CARGO_WAITING7": "57",
    "PERM_REGISTER_DBG_INCOMING_CARGO_WAITING8": "58",
    "PERM_REGISTER_DBG_PRODUCTION_RAW0": "60",
    "PERM_REGISTER_DBG_PRODUCTION_RAW1": "61",
    "PERM_REGISTER_DBG_PRODUCTION_RAW2": "62",
    "PERM_REGISTER_DBG_PRODUCTION_RAW3": "63",
    "PERM_REGISTER_DBG_PRODUCTION_RAW4": "64",
    "PERM_REGISTER_DBG_PRODUCTION_RAW5": "65",
    "PERM_REGISTER_DBG_PRODUCTION_RAW6": "66",
    "PERM_REGISTER_DBG_PRODUCTION_RAW7": "67",
    "PERM_REGISTER_DBG_PRODUCTION_RAW8": "68",
    "PERM_REGISTER_DBG_PRODUCT_0": "69",
    "PERM_REGISTER_DBG_PRODUCT_1": "70",
    "PERM_REGISTER_DBG_PRODUCT_2": "71",
    "PERM_REGISTER_DBG_PRODUCT_3": "72",
    "PERM_REGISTER_DBG_PRODUCT_4": "73",
    "PERM_REGISTER_DBG_PRODUCT_5": "74",
}